# Generated by Django 2.0.2 on 2018-09-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Imágen 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Imágen 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Imágen 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Enlace'),
        ),
    ]
