# Generated by Django 2.0.2 on 2018-09-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180912_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Descripción (Opcional)')),
                ('logo', models.ImageField(upload_to='services/associated', verbose_name='Logo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'asociado',
                'verbose_name_plural': 'asociados',
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='services/service', verbose_name='Imágen 1 (Opcional)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='services/service', verbose_name='Imágen 2 (Opcional)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='services/service', verbose_name='Imágen 3 (Opcional)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Enlace (Opcional)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
    ]
