# Generated by Django 2.0.2 on 2018-09-17 04:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180917_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción (Opcional)'),
        ),
    ]
