# Generated by Django 2.0.2 on 2020-04-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180917_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated',
            name='logo',
            field=models.ImageField(upload_to='services/associated', verbose_name='Logo (400x300 px)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='services/service', verbose_name='Imágen 1 (1200x658 px, Opcional)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='services/service', verbose_name='Imágen 2 (1200x658 px, Opcional)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='services/service', verbose_name='Imágen 3 (1200x658 px, Opcional)'),
        ),
    ]
