# Generated by Django 2.0.2 on 2020-04-28 06:38

from django.db import migrations, models
import django.utils.timezone
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200222_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='father_last_name',
            field=models.CharField(default='apellido_paterno', max_length=50, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='male', max_length=15, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=30.2344, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.FloatField(default=-70.23455, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(default='single', max_length=20, verbose_name='Estado Civil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='example_name', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apodo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.CharField(default='example_rut', max_length=11, verbose_name='Rut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='upload_first_meme_photo',
            field=models.ImageField(default='profiles/meme_photo/example_1', upload_to=registration.models.meme_photo_custom_upload_to, verbose_name='Meme Favorito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='upload_first_track_id',
            field=models.CharField(default='dfGHKLlsle34sndfe45u6', max_length=30, verbose_name='Canción Favorita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='upload_most_love_photo',
            field=models.ImageField(default='profiles/love_photo/example_1', upload_to=registration.models.love_photo_custom_upload_to, verbose_name='Foto Tesoro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profiles/avatar_photo/example_1', upload_to=registration.models.avatar_custom_upload_to, verbose_name='Foto Perfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
    ]
