# Generated by Django 2.0.2 on 2018-09-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('content', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='courses/category', verbose_name='Imágen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorias',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre del Curso')),
                ('initials', models.CharField(max_length=50, verbose_name='Sigla del Curso')),
                ('content', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='courses/course', verbose_name='Imágen')),
                ('managers', models.CharField(max_length=300, verbose_name='Encargado(s)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Ubicación (Opcional)')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección de la Ubicación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/location', verbose_name='Imágen (Opcional)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud (Opcional)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud (Opcional)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Modalidad')),
                ('content', models.TextField(verbose_name='Descripción')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado (Opcional)')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duración (Opcional)')),
                ('period', models.CharField(blank=True, max_length=200, null=True, verbose_name='Periodo (Opcional)')),
                ('inscribed', models.IntegerField(blank=True, null=True, verbose_name='Inscritos (Opcional)')),
                ('quotas', models.IntegerField(blank=True, null=True, verbose_name='Cupos (Opcional)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('location', models.ManyToManyField(to='courses.Location', verbose_name='Ubicaciones')),
            ],
            options={
                'verbose_name': 'modalidad',
                'verbose_name_plural': 'modalidades',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='modality',
            field=models.ManyToManyField(to='courses.Modality', verbose_name='Modalidades'),
        ),
    ]
