# Generated by Django 2.0.2 on 2018-09-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180917_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/course', verbose_name='Imágen (940x567 px)'),
        ),
    ]
