# Generated by Django 2.0.2 on 2018-09-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180918_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shortcontent',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Breve Descripción'),
        ),
    ]
