# Generated by Django 2.0.2 on 2018-09-18 18:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_shortcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='shortcontent',
            field=ckeditor.fields.RichTextField(blank=True, max_length=250, null=True, verbose_name='Breve Descripción'),
        ),
    ]
