# Generated by Django 2.0.2 on 2020-04-28 06:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180918_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='shortcontent',
            field=ckeditor.fields.RichTextField(blank=True, max_length=250, null=True, verbose_name='Breve Descripción (Opcional)'),
        ),
    ]
